#use_frameworks!
#source 'https://github.com/SAMIM-YouHuiKeJi/SAMIMPublicSpecs.git'
#source 'https://github.com/CocoaPods/Specs.git'

target 'SAMIM-MapKit_Example' do
    # pod 'SAMIM-MapKit'
  pod 'SAMIM-MapKit', :path => '../'

  target 'SAMIM-MapKit_Tests' do
    inherit! :search_paths


end
end
